version: "3"
services:
  db:
    image: mariadb
    ports:
      - "32000:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASS}"
      MYSQL_DATABASE: "${MYSQL_DB}"
  web-server:
    build: ./backend
    depends_on:
      - db
    links:
      - db
    ports:
      - "5001:5000"
    command: sh -c "/wait && python -u run.py"
    environment:
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
